### PR TITLE
Fix when using Rack > 1.3.6

### PR DESCRIPTION
**Pull request by chy-causer**
This patch removes some lines which were causing problems with rack > 1.3.6. It also updates the test so that they work with Sinatra < 1.3.2 instead of < 1.0.

This is a direct fix for issue #8

### CODE REVIEW

**Comment by shiftb** [comment]
+1 on this

**Comment by heptat** [comment]
yeah, this works a treat, thanks

**Comment by tlianza** [comment]
This would be great... it seems that without this, rack-flash does not work with modern versions of rack.

**Comment by neiltron** [comment]
:+1:

**Comment by chrismetcalf** [comment]
Please!

**Comment by chy-causer** [comment]
It looks like a gem has been pushed with the fix. Please see #8

**Pull request closed without merging**
